### ISSUE TITLE
falta do diretorio

### ISSUE THREAD

**Issue by vinnyaf** [eftechcombr/bacula#1]
boa tarde notei que esta faltando a configuração do director poderia me informa como posso estar configurando ele para colocar ele em produção, na minha rede da empresa! e isso esta causando uns problemas

**Comment by eduardofraga** [comment]
Os arquivos estão em: docker/etc/

**Comment by vinnyaf** [comment]
então na pagina da web ele não aparece, no caso não consigo mandar uma imagem para que possa ver

**Comment by eduardofraga** [comment]
Segue o caminho completo do arquivo de configuração do director: docker/etc/bacula-dir.conf

**Comment by vinnyaf** [comment]
Bom acredito que eu posso ter me expressado errado, o problema é dentro da página da web, ela não mostra o dir, e quando vou configurar para puxar o cliente de outra máquina da rede ele dá erro também, sendo que esta tudo correto nas permissão

**Comment by vinnyaf** [comment]
pode ver pela imafem em questão
![Screenshot_2](https://github.com/eftechcombr/bacula/assets/13530331/c979f06e-a62b-4fc6-aedf-8c24f7fefbd0)
![Screenshot_3](https://github.com/eftechcombr/bacula/assets/13530331/8a473f47-26e4-4925-9c4d-ceae08d59278)
