### ISSUE TITLE
Errors in sudo for Baculum

### ISSUE THREAD

**Issue by dukegris** [eftechcombr/bacula#11]
In order tu run eftechcombr/baculum:11.0.6-api i need to install sudo so i think you need to change /docker/baculum-api/Dockerfile and add in line 17 sudo \
Then, when you install sudo you could see an error in bacula/docker/baculum-api/sudoers-baculum 
The line 1 is Defaults:apache "'!'"requiretty and must be Defaults:www-data !requiretty. change the user and delte the " and the '

The same it will be for baculum-web

Thx

**Comment by eduardofraga** [comment]
https://github.com/eftechcombr/bacula/blob/0777081f505c437269622e1b6326c592e36bdcb7/docker/baculum-api/Dockerfile#L22
