### ISSUE TITLE
Two of the Six services won't start

### ISSUE THREAD

**Issue by BazRoe** [eftechcombr/bacula#12]
Hello
Excuse me, I am following the steps as you reported them on the readme.

There are a total of 6 services listed in the docker compose.
the client, storage, director and catalog startup fine, but the last two, api and web ( wich should be the GUI ) do not start and exist istantly.
Is there a fix for this or can you help me figure out what i'm doing wrong?
Thank you

**Comment by eduardofraga** [comment]
Resolved with upgrade baculum from 11 to 15
