### ISSUE TITLE
Can't create anything

### ISSUE THREAD

**Issue by FireCulex** [eftechcombr/bacula#14]
Using the web interface anytime I try to create storage or pool etc. it says
Error Error 1000: Internal error. [Notice] tempnam(): file created in the system's temporary directory (@line 141 in file /usr/share/baculum/htdocs/protected/API/Modules/JSONTools.php).

I believe it's a problem with the api?

**Comment by eduardofraga** [comment]
I use baculum is configured as readonly because we use Infrastructure as Code (Iac). 

Try change RO to RW in: 
- /docker/docker-compose.yml 
- /docker/etc

**Comment by FireCulex** [comment]
I'm not familiar with bacula so this is new to me and i'm having a hard time with config syntax so trying to use the gui to get an idea. Changing everything to rw in docker-compose.yml yields no difference.

**Comment by FireCulex** [comment]
setting /etc/baculum to 777 fixed the issue.  Thanks!
